---
HOSTS:
  cisconx-64-1:
    pe_dir: 
    pe_ver: 
    pe_upgrade_dir: 
    pe_upgrade_ver: 
    hypervisor: vmpooler
    platform: cisco_nexus-7-x86_64
    packaging_platform: cisco-wrlinux-5-x86_64
    vrf: management
    ssh:
      user: admin
      password: admin
    template: cisco-nxos-9k-x86_64
    roles:
    - default
CONFIG:
  nfs_server: none
  consoleport: 443
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
  disable_updates: false
  masterless: true
